### ISSUE TITLE
Version 1.4.0 incompatible with holidays v0.13

### ISSUE THREAD

**Issue by tbock** [linuxsoftware/ls.joyous#44]
When updating a project I ran into the below error.  It seems to come from a compatibility issue with holidays v0.13.  When holding holidays to 0.12 or 0.11the error went away. 

   File "/usr/local/lib/python3.8/site-packages/ls/joyous/models/__init__.py", line 12, in <module>
     from .recurring_events import RecurringEventPage
   File "/usr/local/lib/python3.8/site-packages/ls/joyous/models/recurring_events.py", line 40, in <module>
     from ..holidays import Holidays
   File "/usr/local/lib/python3.8/site-packages/ls/joyous/holidays/__init__.py", line 8, in <module>
     from .parser import parseHolidays
   File "/usr/local/lib/python3.8/site-packages/ls/joyous/holidays/parser.py", line 21, in <module>
     _PYTHON_HOLIDAYS_MAP = _createMap(list(python_holidays.__dict__.items()))
   File "/usr/local/lib/python3.8/site-packages/ls/joyous/holidays/parser.py", line 17, in _createMap
     obj = cls()
 TypeError: __init__() missing 2 required positional arguments: 'h1' and 'h2'

Python 3.8
Django 3.1
ls.joyous 1.4.0
wagtail 2.12

**Comment by Eng-Ahmad-Almohammad** [comment]
I am facing the same issue.

**Comment by Mohammad-Abdul-Ghafour** [comment]
Me too facing same issue.

**Comment by bradrice** [comment]
I just tried installing and am getting this error as well. Mine is after a new installation, not a migrate from previous version.

**Comment by paperreduction** [comment]
Pinning the install version of python-holidays to 0.12 would fix the issue. I'm not sure why the dependencies aren't already pinned.

I've fixed the problem and pinned the version. Please see attached PR for your review.

**Comment by bradrice** [comment]
I tried installing again and got holidays==0.13. But now that I know, I downgraded. I'm assuming the change still isn't in master.

**Comment by paperreduction** [comment]
@bradrice No, it doesn't look like my PR has had any action on it. But pinning the older version of holidays should be a good fix for now. Details on the breaking changes in Holidays v0.13 are in the comments on the PR. You'll see it was a change to the imports in holidays that broke joyous, not a feature/functionality change.

**Comment by linuxsoftware** [comment]
Thanks to @paperreduction for the fix.
